from django.urls import path
from .views import (
    MeetingCreateView,
    MeetingListView,
    meeting_detail_view,
    MeetingUpdateView,
    MeetingDeleteView,
    home_page,
    all_requests_list_view,
    meeting_participants_view,
    ArchivedMeetingListView,
    archive_meeting_view,
    meeting_not_found_view,
    edit_attendance_view,
    request_list_view,
    edit_request_view,
    RequestDeleteView,
    edit_announcement_view,
    edit_discussion_view,
    edit_appendix_view,
    advice_list_view,
    edit_advice_view,
    send_resolution_view,
    notification_template_view,
    send_notification_view,
    track_resolution_view,
)

urlpatterns = [
    path("home/", home_page, name="homepage"),
    path("all-requests/", all_requests_list_view, name="all-requests-list"),
    path("", MeetingListView.as_view(), name="meeting-list"),
    path("create/", MeetingCreateView.as_view(), name="meeting-create"),
    path("<int:id>/", meeting_detail_view, name="meeting-detail"),
    path("<int:pk>/edit/", MeetingUpdateView.as_view(), name="edit-meeting"),
    path("<int:pk>/delete/", MeetingDeleteView.as_view(), name="meeting-delete"),
    path("<int:id>/participants/", meeting_participants_view, name="meeting-participants"),
    path("archived/", ArchivedMeetingListView.as_view(), name="archived-meetings"),
    path("<int:id>/archive/", archive_meeting_view, name="archive-meeting"),
    path("meeting-not-found/", meeting_not_found_view, name="meeting-not-found"),
    path("<int:id>/edit-attendances/", edit_attendance_view, name="edit-attendance"),
    path("<int:id>/requests/", request_list_view, name="request-list"),
    path("<int:id>/edit-requests/", edit_request_view, name="edit-requests"),
    path("<int:pk>/request/delete/", RequestDeleteView.as_view(), name="request-delete"),
    path(
        "<int:id>/edit-announcements/",
        edit_announcement_view,
        name="edit-announcements",
    ),
    path("<int:id>/edit-discussions/", edit_discussion_view, name="edit-discussions"),
    path("<int:id>/edit-appendices/", edit_appendix_view, name="edit-appendices"),
    path("<int:id>/advices/", advice_list_view, name="advice-list"),
    path("<int:id>/edit-advices/", edit_advice_view, name="edit-advices"),
    path("<int:id>/send-resolution/", send_resolution_view, name="send-resolution"),
    path("email/", notification_template_view, name="notification-template"),
    path("<int:id>/send-notification/", send_notification_view, name="send-notification"),
    path("track/", track_resolution_view, name="track-resolution"),
]
