# Generated by Django 3.2.8 on 2021-11-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='sex',
            field=models.IntegerField(choices=[(-1, ''), (0, '女性'), (1, '男性')], default=-1),
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('address', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=14)),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='ExternalTeacherProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('school', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('address', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=14)),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('title', models.CharField(max_length=20)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
            ],
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='StudentRepresentativeProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.profile')),
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('school_system', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
            ],
            bases=('accounts.profile',),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
