# Generated by Django 3.2.9 on 2021-11-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='sex',
        ),
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.IntegerField(choices=[(0, '業界專家'), (1, '學生代表'), (2, '校外老師'), (3, '系助理'), (4, '系上老師')], default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('sex', models.IntegerField(choices=[(0, '女性'), (1, '男性')], default=0)),
                ('email', models.EmailField(max_length=254)),
                ('participant_type', models.IntegerField(choices=[(0, '業界專家'), (1, '學生代表'), (2, '校外老師'), (3, '系助理'), (4, '系上老師')], default=0)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('title', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=14)),
                ('company', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('school_system', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
