# Generated by Django 3.2.9 on 2021-12-03 09:25

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': [('request_for_modifying_meeting_minutes', '發出會議紀錄修改請求'), ('create_extempore_motion', '新增臨時動議'), ('mail_result', '寄出開會結果')]},
        ),
        migrations.AlterModelManagers(
            name='participant',
            managers=[
                ('objects', accounts.models.ParticipantManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='sex',
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.IntegerField(choices=[(0, '業界專家'), (1, '學生代表'), (2, '校外老師'), (3, '系助理'), (4, '系上老師')], default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(choices=[(0, '女性'), (1, '男性'), (2, '其他')], default=2)),
                ('phone', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=14)),
                ('company', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=15)),
                ('school_system', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
