# Generated by Django 3.2.9 on 2021-12-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': [('create_edit_request', '發出會議紀錄修改請求'), ('create_extempore_motion', '新增臨時動議'), ('mail_notification', '寄出會議通知'), ('mail_result', '寄出開會結果')]},
        ),
    ]
