# Generated by Django 3.2.8 on 2021-11-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211124_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistant',
            new_name='AssistantProfile',
        ),
        migrations.RenameModel(
            old_name='Professor',
            new_name='ProfessorProfile',
        ),
    ]
