# Generated by Django 3.2.9 on 2022-01-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_participant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'permissions': [('mail_result', '寄出開會結果')]},
        ),
    ]
