# Generated by Django 3.2.9 on 2021-11-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211126_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='participant_type',
        ),
    ]
