# Generated by Django 3.2.9 on 2021-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('chairman', models.CharField(max_length=20)),
                ('minutes_taker', models.CharField(max_length=20)),
            ],
        ),
    ]
