# Generated by Django 3.2.9 on 2021-11-25 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('chairman', models.CharField(max_length=20)),
                ('minutes_taker', models.CharField(max_length=20)),
            ],
        ),
    ]
