# Generated by Django 3.2.9 on 2021-12-12 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='speech',
            field=models.CharField(default='略', max_length=500, verbose_name='主席致詞'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='chairman',
            field=models.CharField(max_length=20, verbose_name='主席'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(verbose_name='開會日期'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(max_length=100, verbose_name='會議地點'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='minutes_taker',
            field=models.CharField(max_length=20, verbose_name='記錄人員'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='會議名稱'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='與會人員'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(max_length=20, verbose_name='會議種類'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField(default=False, verbose_name='出席')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meetings.meeting')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendance_record',
            field=models.ManyToManyField(through='meetings.Attendance', to=settings.AUTH_USER_MODEL, verbose_name='出席紀錄'),
        ),
    ]
