# Generated by Django 3.2.9 on 2021-11-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='uuid',
        ),
    ]
