# Generated by Django 3.2.13 on 2022-06-08 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(verbose_name='建議')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='meetings.meeting', verbose_name='會議')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_advices', to=settings.AUTH_USER_MODEL, verbose_name='與會人員')),
            ],
        ),
    ]
