# Generated by Django 3.2.9 on 2021-12-31 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appendices', to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='與會人員'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='resolution',
            field=models.CharField(default='無', max_length=150, verbose_name='決議'),
        ),
        migrations.AlterField(
            model_name='extemporemotion',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extempore_motions', to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendance_record',
            field=models.ManyToManyField(related_name='attendance', through='meetings.Attendance', to=settings.AUTH_USER_MODEL, verbose_name='出席紀錄'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_meeting', to=settings.AUTH_USER_MODEL, verbose_name='主席'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='minutes_taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='take_minutes_meeting', to=settings.AUTH_USER_MODEL, verbose_name='記錄人員'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='speech',
            field=models.TextField(default='略', max_length=500, verbose_name='主席致詞'),
        ),
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='內容')),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_requests', to='meetings.meeting', verbose_name='會議')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='與會人員')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='edit_request',
            field=models.ManyToManyField(related_name='edit_requests', through='meetings.EditRequest', to=settings.AUTH_USER_MODEL, verbose_name='修改請求'),
        ),
    ]
