# Generated by Django 3.2.9 on 2021-12-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20211223_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='resolution',
            field=models.CharField(default='無', max_length=150, verbose_name='決議'),
        ),
    ]
