# Generated by Django 3.2.9 on 2021-12-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_announcement_discussion_extemporemotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='extemporemotion',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meetings.meeting', verbose_name='會議'),
        ),
    ]
