# Generated by Django 3.2.9 on 2021-12-12 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_auto_20211212_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='與會人員'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='speech',
            field=models.CharField(default='略', max_length=500, verbose_name='主席致詞'),
        ),
    ]
