# Generated by Django 3.2.9 on 2021-12-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20211218_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='會議'),
        ),
    ]
