# Generated by Django 3.2.9 on 2021-12-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_attendance_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='會議'),
        ),
        migrations.AlterField(
            model_name='extemporemotion',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='會議'),
        ),
    ]
