# Generated by Django 3.2.9 on 2021-12-22 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_appendix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendix',
            name='file',
            field=models.FileField(blank=True, upload_to='files', verbose_name='檔案'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting', verbose_name='會議'),
        ),
    ]
