# Generated by Django 3.2.9 on 2021-11-19 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[(0, '女性'), (1, '男性')])),
                ('identity', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.participant')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
            ],
            bases=('participants.participant',),
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.participant')),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('address', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=14)),
            ],
            bases=('participants.participant',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.participant')),
                ('title', models.CharField(max_length=20)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
            ],
            bases=('participants.participant',),
        ),
        migrations.CreateModel(
            name='StudentRepresentative',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='participants.participant')),
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('school_system', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
            ],
            bases=('participants.participant',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.participant')),
                ('school', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('address', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=14)),
            ],
            bases=('participants.participant',),
        ),
    ]
