# Generated by Django 3.2.9 on 2021-11-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
    ]
