# Generated by Django 3.2.9 on 2021-11-19 02:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_participant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.participant')),
                ('company', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=20)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('address', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=14)),
            ],
            bases=('participants.participant',),
        ),
    ]
