# Generated by Django 3.2.9 on 2021-11-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_remove_participant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='identity',
            field=models.IntegerField(choices=[(0, '業界專家'), (1, '學生代表'), (2, '校外老師'), (3, '系助理'), (4, '系上老師')]),
        ),
    ]
