# Generated by Django 3.2.9 on 2021-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='sex',
            field=models.IntegerField(choices=[(0, '男性'), (1, '女性')]),
        ),
    ]
