# Generated by Django 3.2.9 on 2021-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_participant_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='identity',
            field=models.IntegerField(choices=[(-1, '無'), (0, '業界專家'), (1, '學生代表'), (2, '校外老師'), (3, '系助理'), (4, '系上老師')], default=-1),
        ),
    ]
